export enum Category {
  BAKERY = "BAKERY",
  FRUITANDVEGETABLES = "FRUITANDVEGETABLES",
  MEATANDFISH = "MEATANDFISH",
  DRINKS = "DRINKS",
  KITCHEN = "KITCHEN",
  SPECIALNUTRITION = "SPECIALNUTRITION",
  BABY = "BABY",
  PHARMACY = "PHARMACY",
}

export enum Subcategory {
  BAKERY = "BAKERY",
  VEGETABLES = "VEGETABLES",
  FRUIT = "FRUIT",
  DRINKS = "DRINKS",
  KITCHEN = "KITCHEN",
  SPECIALNUTRITION = "SPECIALNUTRITION",
  FISH = "FISH",
  MEAT = "MEAT",
}

export interface CategoryItem {
  id: number;
  title: string;
}
